name: 'Gitflow Workflow (release/hotfix)'
description: 'Implementation of Gitflow with Github Actions (release/hotfix)'
author: 'domix24'
inputs:
  dev_branch:
    required: true
    description: 'name of dev branch'
    default: 'develop'
  main_branch:
    required: true
    description: 'name of main branch'
    default: 'main'
  github_token:
    required: true
    description: 'github token'
runs:
  using: 'node20'
  main: 'dist/index.js'
