name: 'Gitflow Workflow'
description: 'Implementation of Gitflow with Github Actions'
author: 'domix24'
inputs:
  dev_branch:
    required: true
    description: 'name of dev branch'
    default: 'develop'
  main_branch:
    required: true
    description: 'name of main branch'
    default: 'main'
runs:
  using: 'node20'
  main: 'dist/index.js'
