name: Dependabot Auto-Merge

on:
  pull_request:

permissions: read-all

jobs:
  auto-merge:
    name: Merge
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@47796943e72f39c7a9069c2fa0e39dc2cc9299f7
        with:
          target: any
          github-token: ${{ secrets.GITHUB_TOKEN }}
