on:
  pull_request:
    types:
      - closed
    branches:
      - main

name: Release Management

permissions: read-all

jobs:
  release_management:
    name: Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          persist-credentials: false
      - name: Build
        uses: domix24/action-gitflow@945ce6c2c663f2ea96ba87ea93d7022c8fa53e66
        with:
          dev_branch: develop
          main_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
